"""no_poassword

Revision ID: be0737944a1f
Revises: 7d001da80c9d
Create Date: 2021-11-26 15:08:01.637197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be0737944a1f'
down_revision = '7d001da80c9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_name_key', 'users', type_='unique')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_name_key', 'users', ['name'])
    # ### end Alembic commands ###
