import os

PROJECT_NAME = "chat"

API_PREFIX = "/api"

ENV = os.environ.get("ENV", "local")

SQLALCHEMY_TRACK_MODIFICATIONS = False

STATIC_DIR = "static"

POSTGRES_USER = os.environ.get("POSTGRES_USER")
POSTGRES_PASSWORD = os.environ.get("POSTGRES_PASSWORD")
POSTGRES_DB = os.environ.get("POSTGRES_DB")
POSTGRES_HOST = os.environ.get("POSTGRES_HOST", "chat-db")
POSTGRES_PORT = os.environ.get("POSTGRES_PORT", "5432")

SQLALCHEMY_DATABASE_URI = f"postgresql+psycopg2://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}"
SECRET_KEY = os.environ.get("SECRET_KEY")

LIBRE_TRANSLATE_API_KEY = os.environ.get("LIBRE_TRANSLATE_API_KEY")
